apiVersion: v1
kind: Secret
metadata:
  name:  account-statement-backend-secret
type: Opaque
stringData:
  spring.datasource.url: "jdbc:sqlserver://10.200.200.122:1433;databaseName=kbrfq;encrypt=true;trustServerCertificate=true"
  spring.datasource.username: "ian.sikobe"
  spring.datasource.password: "Sikobe1+"
  rfq.app.staticOtpValue: "70000"
  spring.mail.username: "rfqkb@kingdombankltd.co.ke"
  spring.mail.password: "Coop@1234"
  spring.mail.from: "rfqkb@kingdombankltd.co.ke"
  jwt.secretKey: "K8dfUKdsfhadshj9001X"
  soa.auth.client_id: "rTgfTloyBPkJrsezhiosWnch"
  soa.auth.client_secret: "V-mkikJMRhZkl-mIwZMWBdQvWopftTbdnMhv"
  
  
  
  
  
  
  
  
  
  



